--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apartment_likes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apartment_likes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    apartment_id bigint NOT NULL,
    is_liked boolean DEFAULT false NOT NULL
);


ALTER TABLE public.apartment_likes OWNER TO postgres;

--
-- Name: apartment_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apartment_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apartment_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apartments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apartments (
    id bigint NOT NULL,
    apartment_description text,
    rent real,
    photos json,
    amenities_available json,
    is_available boolean,
    user_id uuid,
    start_date bigint,
    beds smallint,
    baths smallint,
    created_at timestamp with time zone DEFAULT now(),
    end_date bigint,
    location gis.geography(Point,4326),
    address text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.apartments OWNER TO postgres;

--
-- Name: marketplaces; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marketplaces (
    id bigint NOT NULL,
    created_at bigint NOT NULL,
    name text,
    category json,
    description text,
    photos json,
    price integer,
    link json,
    period json,
    is_available boolean,
    user_id uuid,
    location gis.geography(Point,4326),
    address text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.marketplaces OWNER TO postgres;

--
-- Name: TABLE marketplaces; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.marketplaces IS 'place to sell products from student to student';


--
-- Name: market_place_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marketplaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marketplaces_likes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marketplaces_likes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid DEFAULT gen_random_uuid(),
    marketplace_id bigint NOT NULL,
    is_liked boolean DEFAULT false NOT NULL
);


ALTER TABLE public.marketplaces_likes OWNER TO postgres;

--
-- Name: marketplace_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marketplaces_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marketplace_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sublet_likes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sublet_likes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    sublet_id bigint NOT NULL,
    is_liked boolean DEFAULT false NOT NULL
);


ALTER TABLE public.sublet_likes OWNER TO postgres;

--
-- Name: sublet_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sublet_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sublet_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sublets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sublets (
    id bigint NOT NULL,
    room_description text,
    roommate_description text,
    roommate_gender_pref text,
    rent real,
    photos json,
    amenities_available json,
    room_type text,
    is_available boolean,
    user_id uuid,
    start_date bigint,
    end_date bigint,
    beds smallint,
    baths smallint,
    created_at timestamp with time zone DEFAULT now(),
    location gis.geography(Point,4326),
    address text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.sublets OWNER TO postgres;

--
-- Name: TABLE sublets; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.sublets IS 'table containing all the sublets post request data';


--
-- Name: user_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_details (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    full_name text DEFAULT ''::text,
    email text DEFAULT ''::text,
    phone text,
    profile_image text DEFAULT ''::text,
    city text DEFAULT ''::text,
    selected_course_name text DEFAULT ''::text,
    gender character varying,
    undergrad_college_name text DEFAULT ''::text,
    birth_date timestamp without time zone,
    person_type character varying,
    prefs json,
    primary_lang text,
    other_lang text,
    work_experience smallint,
    smoking_habit character varying,
    habits json,
    hobbies text,
    drinking_habit character varying DEFAULT ''::character varying,
    food_habit text,
    cooking_skill text,
    cleanliness_habit character varying,
    state text,
    bio text,
    room_type text,
    flatmates_gender_prefs text,
    country text,
    user_deleted boolean DEFAULT false,
    user_deleted_date timestamp with time zone,
    intake_period text,
    intake_year smallint,
    has_roommate_found boolean DEFAULT false,
    user_data_completed boolean DEFAULT false,
    college text DEFAULT ''::text
);


ALTER TABLE public.user_details OWNER TO postgres;

--
-- Name: TABLE user_details; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.user_details IS 'Table that contains all the user details';


--
-- Name: apartment_likes apartment_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apartment_likes
    ADD CONSTRAINT apartment_likes_pkey PRIMARY KEY (id);


--
-- Name: apartment_likes apartment_likes_sublet_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apartment_likes
    ADD CONSTRAINT apartment_likes_sublet_id_key UNIQUE (apartment_id);


--
-- Name: apartments apartments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apartments
    ADD CONSTRAINT apartments_pkey PRIMARY KEY (id);


--
-- Name: marketplaces market_place_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marketplaces
    ADD CONSTRAINT market_place_pkey PRIMARY KEY (id);


--
-- Name: marketplaces_likes marketplace_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marketplaces_likes
    ADD CONSTRAINT marketplace_likes_pkey PRIMARY KEY (id);


--
-- Name: marketplaces_likes marketplaces_likes_marketplace_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marketplaces_likes
    ADD CONSTRAINT marketplaces_likes_marketplace_id_key UNIQUE (marketplace_id);


--
-- Name: sublet_likes sublet_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sublet_likes
    ADD CONSTRAINT sublet_likes_pkey PRIMARY KEY (id);


--
-- Name: sublet_likes sublet_likes_sublet_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sublet_likes
    ADD CONSTRAINT sublet_likes_sublet_id_key UNIQUE (sublet_id);


--
-- Name: sublets sublets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sublets
    ADD CONSTRAINT sublets_pkey PRIMARY KEY (id);


--
-- Name: user_details user_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_details
    ADD CONSTRAINT user_details_pkey PRIMARY KEY (id);


--
-- Name: apartments_location_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX apartments_location_idx ON public.apartments USING gist (location);


--
-- Name: marketplaces_location_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX marketplaces_location_idx ON public.marketplaces USING gist (location);


--
-- Name: sublets_location_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sublets_location_idx ON public.sublets USING gist (location);


--
-- Name: apartment_likes apartment_likes_apartment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apartment_likes
    ADD CONSTRAINT apartment_likes_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES public.apartments(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: apartment_likes apartment_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apartment_likes
    ADD CONSTRAINT apartment_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_details(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: marketplaces_likes marketplaces_likes_marketplace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marketplaces_likes
    ADD CONSTRAINT marketplaces_likes_marketplace_id_fkey FOREIGN KEY (marketplace_id) REFERENCES public.marketplaces(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: marketplaces_likes marketplaces_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marketplaces_likes
    ADD CONSTRAINT marketplaces_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_details(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: sublet_likes sublet_likes_sublet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sublet_likes
    ADD CONSTRAINT sublet_likes_sublet_id_fkey FOREIGN KEY (sublet_id) REFERENCES public.sublets(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: sublet_likes sublet_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sublet_likes
    ADD CONSTRAINT sublet_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_details(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_details user_details_college_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_details
    ADD CONSTRAINT user_details_college_fkey FOREIGN KEY (college) REFERENCES const.universities(title) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: marketplaces_likes Auth Access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Auth Access" ON public.marketplaces_likes TO authenticated USING (true);


--
-- Name: sublet_likes Auth Access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Auth Access" ON public.sublet_likes USING (true);


--
-- Name: user_details Auth Users Access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Auth Users Access" ON public.user_details USING (true);


--
-- Name: marketplaces Enable access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable access for all users" ON public.marketplaces USING (true);


--
-- Name: apartment_likes; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.apartment_likes ENABLE ROW LEVEL SECURITY;

--
-- Name: apartment_likes apartment_likes; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY apartment_likes ON public.apartment_likes USING (true);


--
-- Name: apartments; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.apartments ENABLE ROW LEVEL SECURITY;

--
-- Name: apartments apartments; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY apartments ON public.apartments USING (true);


--
-- Name: marketplaces; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.marketplaces ENABLE ROW LEVEL SECURITY;

--
-- Name: marketplaces_likes; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.marketplaces_likes ENABLE ROW LEVEL SECURITY;

--
-- Name: sublet_likes; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.sublet_likes ENABLE ROW LEVEL SECURITY;

--
-- Name: sublets; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.sublets ENABLE ROW LEVEL SECURITY;

--
-- Name: sublets sublets; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY sublets ON public.sublets USING (true);


--
-- Name: user_details; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.user_details ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE apartment_likes; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.apartment_likes TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.apartment_likes TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.apartment_likes TO service_role;


--
-- Name: SEQUENCE apartment_likes_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.apartment_likes_id_seq TO anon;
GRANT ALL ON SEQUENCE public.apartment_likes_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.apartment_likes_id_seq TO service_role;


--
-- Name: TABLE apartments; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.apartments TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.apartments TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.apartments TO service_role;


--
-- Name: TABLE marketplaces; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.marketplaces TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.marketplaces TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.marketplaces TO service_role;


--
-- Name: SEQUENCE market_place_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.market_place_id_seq TO anon;
GRANT ALL ON SEQUENCE public.market_place_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.market_place_id_seq TO service_role;


--
-- Name: TABLE marketplaces_likes; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.marketplaces_likes TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.marketplaces_likes TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.marketplaces_likes TO service_role;


--
-- Name: SEQUENCE marketplace_likes_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.marketplace_likes_id_seq TO anon;
GRANT ALL ON SEQUENCE public.marketplace_likes_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.marketplace_likes_id_seq TO service_role;


--
-- Name: TABLE sublet_likes; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.sublet_likes TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.sublet_likes TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.sublet_likes TO service_role;


--
-- Name: SEQUENCE sublet_likes_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.sublet_likes_id_seq TO anon;
GRANT ALL ON SEQUENCE public.sublet_likes_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.sublet_likes_id_seq TO service_role;


--
-- Name: TABLE sublets; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.sublets TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.sublets TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.sublets TO service_role;


--
-- Name: TABLE user_details; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.user_details TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.user_details TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.user_details TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

