--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: prod; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA prod;


ALTER SCHEMA prod OWNER TO pg_database_owner;

--
-- Name: SCHEMA prod; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA prod IS 'Nesters Prod Schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apartment_likes; Type: TABLE; Schema: prod; Owner: postgres
--

CREATE TABLE prod.apartment_likes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    apartment_id bigint NOT NULL,
    is_liked boolean DEFAULT false NOT NULL
);


ALTER TABLE prod.apartment_likes OWNER TO postgres;

--
-- Name: apartment_likes_id_seq; Type: SEQUENCE; Schema: prod; Owner: postgres
--

ALTER TABLE prod.apartment_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME prod.apartment_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apartments; Type: TABLE; Schema: prod; Owner: postgres
--

CREATE TABLE prod.apartments (
    id bigint NOT NULL,
    apartment_description text,
    rent real,
    photos json,
    amenities_available json,
    is_available boolean,
    user_id uuid,
    start_date bigint,
    beds smallint,
    baths smallint,
    created_at timestamp with time zone DEFAULT now(),
    end_date bigint,
    location gis.geography(Point,4326),
    address text DEFAULT ''::text NOT NULL
);


ALTER TABLE prod.apartments OWNER TO postgres;

--
-- Name: marketplaces; Type: TABLE; Schema: prod; Owner: postgres
--

CREATE TABLE prod.marketplaces (
    id bigint NOT NULL,
    created_at bigint NOT NULL,
    name text,
    category json,
    description text,
    photos json,
    price integer,
    link json,
    period json,
    is_available boolean,
    user_id uuid,
    location gis.geography(Point,4326),
    address text DEFAULT ''::text NOT NULL
);


ALTER TABLE prod.marketplaces OWNER TO postgres;

--
-- Name: TABLE marketplaces; Type: COMMENT; Schema: prod; Owner: postgres
--

COMMENT ON TABLE prod.marketplaces IS 'Place to sell products from student to student';


--
-- Name: market_place_id_seq; Type: SEQUENCE; Schema: prod; Owner: postgres
--

ALTER TABLE prod.marketplaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME prod.market_place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marketplaces_likes; Type: TABLE; Schema: prod; Owner: postgres
--

CREATE TABLE prod.marketplaces_likes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid DEFAULT gen_random_uuid(),
    marketplace_id bigint NOT NULL,
    is_liked boolean DEFAULT false NOT NULL
);


ALTER TABLE prod.marketplaces_likes OWNER TO postgres;

--
-- Name: marketplace_likes_id_seq; Type: SEQUENCE; Schema: prod; Owner: postgres
--

ALTER TABLE prod.marketplaces_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME prod.marketplace_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sublet_likes; Type: TABLE; Schema: prod; Owner: postgres
--

CREATE TABLE prod.sublet_likes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    sublet_id bigint NOT NULL,
    is_liked boolean DEFAULT false NOT NULL
);


ALTER TABLE prod.sublet_likes OWNER TO postgres;

--
-- Name: sublet_likes_id_seq; Type: SEQUENCE; Schema: prod; Owner: postgres
--

ALTER TABLE prod.sublet_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME prod.sublet_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sublets; Type: TABLE; Schema: prod; Owner: postgres
--

CREATE TABLE prod.sublets (
    id bigint NOT NULL,
    room_description text,
    roommate_description text,
    roommate_gender_pref text,
    rent real,
    photos json,
    amenities_available json,
    room_type text,
    is_available boolean,
    user_id uuid,
    start_date bigint,
    end_date bigint,
    beds smallint,
    baths smallint,
    created_at timestamp with time zone DEFAULT now(),
    location gis.geography(Point,4326),
    address text DEFAULT ''::text NOT NULL
);


ALTER TABLE prod.sublets OWNER TO postgres;

--
-- Name: TABLE sublets; Type: COMMENT; Schema: prod; Owner: postgres
--

COMMENT ON TABLE prod.sublets IS 'Table containing all the sublets post request data';


--
-- Name: user_details; Type: TABLE; Schema: prod; Owner: postgres
--

CREATE TABLE prod.user_details (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    full_name text DEFAULT ''::text,
    email text DEFAULT ''::text,
    phone text,
    profile_image text DEFAULT ''::text,
    city text DEFAULT ''::text,
    selected_course_name text DEFAULT ''::text,
    gender character varying,
    college text DEFAULT ''::text NOT NULL,
    undergrad_college_name text DEFAULT ''::text,
    birth_date timestamp without time zone,
    person_type character varying,
    prefs json,
    primary_lang text,
    other_lang text,
    work_experience smallint,
    smoking_habit character varying,
    habits json,
    hobbies text,
    drinking_habit character varying DEFAULT ''::character varying,
    food_habit text,
    cooking_skill text,
    cleanliness_habit character varying,
    state text,
    bio text,
    room_type text,
    flatmates_gender_prefs text,
    country text,
    user_deleted boolean DEFAULT false,
    user_deleted_date timestamp with time zone,
    intake_period text,
    intake_year smallint,
    has_roommate_found boolean DEFAULT false,
    user_data_completed boolean DEFAULT false
);


ALTER TABLE prod.user_details OWNER TO postgres;

--
-- Name: TABLE user_details; Type: COMMENT; Schema: prod; Owner: postgres
--

COMMENT ON TABLE prod.user_details IS 'Table that contains all the user details';


--
-- Name: apartment_likes apartment_likes_pkey; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.apartment_likes
    ADD CONSTRAINT apartment_likes_pkey PRIMARY KEY (id);


--
-- Name: apartment_likes apartment_likes_sublet_id_key; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.apartment_likes
    ADD CONSTRAINT apartment_likes_sublet_id_key UNIQUE (apartment_id);


--
-- Name: apartments apartments_pkey; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.apartments
    ADD CONSTRAINT apartments_pkey PRIMARY KEY (id);


--
-- Name: marketplaces market_place_pkey; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.marketplaces
    ADD CONSTRAINT market_place_pkey PRIMARY KEY (id);


--
-- Name: marketplaces_likes marketplace_likes_pkey; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.marketplaces_likes
    ADD CONSTRAINT marketplace_likes_pkey PRIMARY KEY (id);


--
-- Name: marketplaces_likes marketplaces_likes_marketplace_id_key; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.marketplaces_likes
    ADD CONSTRAINT marketplaces_likes_marketplace_id_key UNIQUE (marketplace_id);


--
-- Name: sublet_likes sublet_likes_pkey; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.sublet_likes
    ADD CONSTRAINT sublet_likes_pkey PRIMARY KEY (id);


--
-- Name: sublet_likes sublet_likes_sublet_id_key; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.sublet_likes
    ADD CONSTRAINT sublet_likes_sublet_id_key UNIQUE (sublet_id);


--
-- Name: sublets sublets_pkey; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.sublets
    ADD CONSTRAINT sublets_pkey PRIMARY KEY (id);


--
-- Name: user_details user_details_pkey; Type: CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.user_details
    ADD CONSTRAINT user_details_pkey PRIMARY KEY (id);


--
-- Name: apartments_location_idx; Type: INDEX; Schema: prod; Owner: postgres
--

CREATE INDEX apartments_location_idx ON prod.apartments USING gist (location);


--
-- Name: marketplaces_location_idx; Type: INDEX; Schema: prod; Owner: postgres
--

CREATE INDEX marketplaces_location_idx ON prod.marketplaces USING gist (location);


--
-- Name: sublets_location_idx; Type: INDEX; Schema: prod; Owner: postgres
--

CREATE INDEX sublets_location_idx ON prod.sublets USING gist (location);


--
-- Name: apartment_likes apartment_likes_apartment_id_fkey; Type: FK CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.apartment_likes
    ADD CONSTRAINT apartment_likes_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES prod.apartments(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: apartment_likes apartment_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.apartment_likes
    ADD CONSTRAINT apartment_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES prod.user_details(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: marketplaces_likes marketplaces_likes_marketplace_id_fkey; Type: FK CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.marketplaces_likes
    ADD CONSTRAINT marketplaces_likes_marketplace_id_fkey FOREIGN KEY (marketplace_id) REFERENCES prod.marketplaces(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: marketplaces_likes marketplaces_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.marketplaces_likes
    ADD CONSTRAINT marketplaces_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES prod.user_details(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: sublet_likes sublet_likes_sublet_id_fkey; Type: FK CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.sublet_likes
    ADD CONSTRAINT sublet_likes_sublet_id_fkey FOREIGN KEY (sublet_id) REFERENCES prod.sublets(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: sublet_likes sublet_likes_user_id_fkey; Type: FK CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.sublet_likes
    ADD CONSTRAINT sublet_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES prod.user_details(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_details user_details_college_fkey; Type: FK CONSTRAINT; Schema: prod; Owner: postgres
--

ALTER TABLE ONLY prod.user_details
    ADD CONSTRAINT user_details_college_fkey FOREIGN KEY (college) REFERENCES const.universities(title) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: user_details  Insert User Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY " Insert User Policy" ON prod.user_details FOR INSERT TO authenticated, service_role WITH CHECK ((( SELECT auth.uid() AS uid) = id));


--
-- Name: apartment_likes Apartment Likes Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Apartment Likes Policy" ON prod.apartment_likes TO authenticated, service_role USING (true);


--
-- Name: apartments Delete Apartment Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Delete Apartment Policy" ON prod.apartments FOR DELETE TO authenticated, service_role USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: marketplaces Delete Marketplaces Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Delete Marketplaces Policy" ON prod.marketplaces FOR DELETE TO authenticated, service_role USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: sublets Delete Sublet Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Delete Sublet Policy" ON prod.sublets FOR DELETE TO authenticated, service_role USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: user_details Delete User Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Delete User Policy" ON prod.user_details FOR DELETE TO authenticated, service_role USING ((( SELECT auth.uid() AS uid) = id));


--
-- Name: marketplaces Enable insert for users based on user_id; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Enable insert for users based on user_id" ON prod.marketplaces FOR INSERT TO authenticated, service_role WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: apartments Insert Apartment Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Insert Apartment Policy" ON prod.apartments FOR INSERT TO authenticated, service_role WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: sublets Insert Sublet Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Insert Sublet Policy" ON prod.sublets FOR INSERT TO authenticated, service_role WITH CHECK (true);


--
-- Name: marketplaces_likes Marketplace Likes Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Marketplace Likes Policy" ON prod.marketplaces_likes TO authenticated, service_role USING (true);


--
-- Name: apartments Select Apartment Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Select Apartment Policy" ON prod.apartments FOR SELECT TO authenticated, service_role USING (true);


--
-- Name: marketplaces Select Marketplace Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Select Marketplace Policy" ON prod.marketplaces FOR SELECT TO authenticated, service_role USING (true);


--
-- Name: sublets Select Sublet Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Select Sublet Policy" ON prod.sublets FOR SELECT TO authenticated, service_role USING (true);


--
-- Name: user_details Select User Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Select User Policy" ON prod.user_details FOR SELECT USING (true);


--
-- Name: sublet_likes Sublet Likes Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Sublet Likes Policy" ON prod.sublet_likes TO authenticated, service_role USING (true);


--
-- Name: apartments Update Apartment Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Update Apartment Policy" ON prod.apartments FOR UPDATE TO authenticated, service_role USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: marketplaces Update Marketplaces Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Update Marketplaces Policy" ON prod.marketplaces FOR UPDATE TO authenticated, service_role USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: sublets Update Sublet Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Update Sublet Policy" ON prod.sublets FOR UPDATE TO authenticated, service_role USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: user_details Update User Policy; Type: POLICY; Schema: prod; Owner: postgres
--

CREATE POLICY "Update User Policy" ON prod.user_details FOR UPDATE TO authenticated, service_role USING ((( SELECT auth.uid() AS uid) = id));


--
-- Name: apartment_likes; Type: ROW SECURITY; Schema: prod; Owner: postgres
--

ALTER TABLE prod.apartment_likes ENABLE ROW LEVEL SECURITY;

--
-- Name: apartments; Type: ROW SECURITY; Schema: prod; Owner: postgres
--

ALTER TABLE prod.apartments ENABLE ROW LEVEL SECURITY;

--
-- Name: marketplaces; Type: ROW SECURITY; Schema: prod; Owner: postgres
--

ALTER TABLE prod.marketplaces ENABLE ROW LEVEL SECURITY;

--
-- Name: marketplaces_likes; Type: ROW SECURITY; Schema: prod; Owner: postgres
--

ALTER TABLE prod.marketplaces_likes ENABLE ROW LEVEL SECURITY;

--
-- Name: sublet_likes; Type: ROW SECURITY; Schema: prod; Owner: postgres
--

ALTER TABLE prod.sublet_likes ENABLE ROW LEVEL SECURITY;

--
-- Name: sublets; Type: ROW SECURITY; Schema: prod; Owner: postgres
--

ALTER TABLE prod.sublets ENABLE ROW LEVEL SECURITY;

--
-- Name: user_details; Type: ROW SECURITY; Schema: prod; Owner: postgres
--

ALTER TABLE prod.user_details ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA prod; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA prod TO postgres;
GRANT USAGE ON SCHEMA prod TO anon;
GRANT USAGE ON SCHEMA prod TO authenticated;
GRANT USAGE ON SCHEMA prod TO service_role;


--
-- Name: TABLE apartment_likes; Type: ACL; Schema: prod; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.apartment_likes TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.apartment_likes TO service_role;


--
-- Name: SEQUENCE apartment_likes_id_seq; Type: ACL; Schema: prod; Owner: postgres
--

GRANT ALL ON SEQUENCE prod.apartment_likes_id_seq TO authenticated;
GRANT ALL ON SEQUENCE prod.apartment_likes_id_seq TO service_role;


--
-- Name: TABLE apartments; Type: ACL; Schema: prod; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.apartments TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.apartments TO service_role;


--
-- Name: TABLE marketplaces; Type: ACL; Schema: prod; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.marketplaces TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.marketplaces TO service_role;


--
-- Name: SEQUENCE market_place_id_seq; Type: ACL; Schema: prod; Owner: postgres
--

GRANT ALL ON SEQUENCE prod.market_place_id_seq TO authenticated;
GRANT ALL ON SEQUENCE prod.market_place_id_seq TO service_role;


--
-- Name: TABLE marketplaces_likes; Type: ACL; Schema: prod; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.marketplaces_likes TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.marketplaces_likes TO service_role;


--
-- Name: SEQUENCE marketplace_likes_id_seq; Type: ACL; Schema: prod; Owner: postgres
--

GRANT ALL ON SEQUENCE prod.marketplace_likes_id_seq TO authenticated;
GRANT ALL ON SEQUENCE prod.marketplace_likes_id_seq TO service_role;


--
-- Name: TABLE sublet_likes; Type: ACL; Schema: prod; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.sublet_likes TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.sublet_likes TO service_role;


--
-- Name: SEQUENCE sublet_likes_id_seq; Type: ACL; Schema: prod; Owner: postgres
--

GRANT ALL ON SEQUENCE prod.sublet_likes_id_seq TO authenticated;
GRANT ALL ON SEQUENCE prod.sublet_likes_id_seq TO service_role;


--
-- Name: TABLE sublets; Type: ACL; Schema: prod; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.sublets TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.sublets TO service_role;


--
-- Name: TABLE user_details; Type: ACL; Schema: prod; Owner: postgres
--

GRANT SELECT ON TABLE prod.user_details TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.user_details TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE prod.user_details TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: prod; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA prod GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA prod GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA prod GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

