create table public.user_details (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  full_name text null default ''::text,
  email text null default ''::text,
  phone text null,
  profile_image text null default ''::text,
  city text null default ''::text,
  selected_college_name text null default ''::text,
  selected_course_name text null default ''::text,
  gender character varying null,
  undergrad_college_name text null default ''::text,
  birth_date timestamp without time zone null,
  person_type character varying null,
  prefs json null,
  primary_lang text null,
  other_lang text null,
  work_experience smallint null,
  smoking_habit character varying null,
  habits json null,
  hobbies text null,
  drinking_habit character varying null default ''::character varying,
  food_habit text null,
  cooking_skill text null,
  cleanliness_habit character varying null,
  state text null,
  bio text null,
  room_type text null,
  flatmates_gender_prefs text null,
  country text null,
  user_deleted boolean null default false,
  user_deleted_date timestamp with time zone null,
  constraint user_details_pkey primary key (id)
) TABLESPACE pg_default;

create table public.sublets (
  id bigint not null,
  room_description text null,
  roommate_description text null,
  roommate_gender_pref text null,
  rent real null,
  photos json null,
  amenities_available json null,
  room_type text null,
  location json null,
  is_available boolean null,
  user_id text null,
  start_date bigint null,
  end_date bigint null,
  beds smallint null,
  baths smallint null,
  created_at timestamp with time zone null default now(),
  constraint sublets_pkey primary key (id)
) TABLESPACE pg_default;

create table public.sublet_likes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  sublet_id bigint not null,
  is_liked boolean not null default false,
  constraint sublet_likes_pkey primary key (id),
  constraint sublet_likes_sublet_id_key unique (sublet_id),
  constraint sublet_likes_sublet_id_fkey foreign KEY (sublet_id) references sublets (id) on update CASCADE on delete CASCADE,
  constraint sublet_likes_user_id_fkey foreign KEY (user_id) references user_details (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.marketplaces (
  id bigint generated by default as identity not null,
  created_at bigint not null,
  name text null,
  category json null,
  description text null,
  photos json null,
  price integer null,
  link json null,
  location json null,
  period json null,
  is_available boolean null,
  user_id text null,
  constraint market_place_pkey primary key (id)
) TABLESPACE pg_default;

create table public.marketplaces_likes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid (),
  marketplace_id bigint not null,
  is_liked boolean not null default false,
  constraint marketplace_likes_pkey primary key (id),
  constraint marketplaces_likes_marketplace_id_key unique (marketplace_id),
  constraint marketplaces_likes_marketplace_id_fkey foreign KEY (marketplace_id) references public.marketplaces (id) on update CASCADE on delete CASCADE,
  constraint marketplaces_likes_user_id_fkey foreign KEY (user_id) references public.user_details (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.apartments (
  id bigint not null,
  apartment_description text null,
  rent real null,
  photos json null,
  amenities_available json null,
  location json null,
  is_available boolean null,
  user_id text null,
  start_date bigint null,
  beds smallint null,
  baths smallint null,
  created_at timestamp with time zone null default now(),
  end_date bigint null,
  constraint apartments_pkey primary key (id)
) TABLESPACE pg_default;

create table public.apartment_likes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  apartment_id bigint not null,
  is_liked boolean not null default false,
  constraint apartment_likes_pkey primary key (id),
  constraint apartment_likes_sublet_id_key unique (apartment_id),
  constraint apartment_likes_apartment_id_fkey foreign KEY (apartment_id) references apartments (id) on update CASCADE on delete CASCADE,
  constraint apartment_likes_user_id_fkey foreign KEY (user_id) references user_details (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.masters (
  id bigint generated by default as identity not null,
  title character varying not null,
  constraint masters_pkey primary key (id)
) TABLESPACE pg_default;

create table public.marketplaces_categories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  constraint market_place_categories_pkey primary key (id)
) TABLESPACE pg_default;

create table public.indian_states (
  id bigint generated by default as identity not null,
  name text null,
  constraint indian_states_pkey primary key (id)
) TABLESPACE pg_default;

create table public.indian_languages (
  id bigint generated by default as identity not null,
  name text null,
  constraint indian_languages_pkey primary key (id)
) TABLESPACE pg_default;

create table public.universities (
  id bigint generated by default as identity not null,
  country text null,
  city text null,
  title text null,
  logo text null,
  score double precision null,
  rank_display text null,
  region text null,
  constraint universities_pkey primary key (id),
  constraint universities_id_key unique (id)
) TABLESPACE pg_default;