name: Nesters Release Build Workflow

on:
  push:
    branches:
      - prod
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.4"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Object Box
        run: flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Store Version
        run: |
          version=$(grep "version" pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f1 | tr -d '\r')
          version_code=$(grep "version" pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f2 | tr -d '\r')
          echo "version=$version" >> $GITHUB_ENV
          echo "version_code=$version_code" >> $GITHUB_ENV
      
      - name: Setup Keystore
        run: |
          echo ${{ secrets.BASE64_ENCODE_GOOGLE_SERVICES }} | base64 -d > android/app/google-services.json
          echo ${{ secrets.BASE64_ENCODED_KEY_PROPERTIES }} | base64 -d > android/key.properties
          echo ${{ secrets.BASE64_ENCODED_KEYSTORE }} | base64 -d > keystores/release-keystore.jks
          echo ${{ secrets.ENCODED_ENV }} | base64 -d > .env

      - name: Build Nesters Release
        run: |
          echo "Building Nesters release - Version: ${{ env.version }}"
          flutter build apk --release

      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: Nesters_v${{ env.version }}.apk
          path: build/app/outputs/flutter-apk/app-release.apk
        
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.version }}+${{ env.version_code }}
          release_name: Nesters v${{ env.version }}
          body: "Release version ${{ env.version }} of Nesters."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: Nesters_v${{ env.version }}.apk
          asset_content_type: application/vnd.android.package-archive
          
      - name: Cleanup
        run: |
          rm android/app/google-services.json
          rm android/key.properties
          rm keystores/release-keystore.jks